class_name: ilms.training.Trainer
lr: 5e-4
num_epochs: 500
early_stopping_patience: 50
early_stopping_grace: 0.1
eval_every: 10
seed: 3771
checkpoint: /work3/s210527/celeba_models/${general.project_name}/${general.run_name}/
checkpoint_name: last_checkpoint.pickle
resume: false