class_name: ilms.training.Trainer
lr: 0.001
max_steps: 2000000
val_steps: 50
early_stopping_patience: 2
eval_every: 2000
seed: 3771
checkpoint: ./model_checkpoints/${general.project_name}/${ general.run_name}/
resume: false